[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "epistemic-labelled-tableau"
package_dir={'':'src'}
version = "1.0.1"
description = "Theorem prover based on tableau system"
readme = "README.md"
authors = [
  { name="Carlos Aguilera Ventura"},
  { name="Fernando Soler Toscano"},
]
