[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Basoa"
version = "0.0.1"
authors = [ { name="Carlos Aguilera Ventura"} ]
description = "Tableau system"
readme = "README.md"
requires-python = ">=3.7"

